spring.application.name=pos-service-revamp

# Database
spring.datasource.url=jdbc:postgresql://157.10.161.207:5432/pos-db-revamp
spring.datasource.username=postgres
spring.datasource.password=ShaninHanan23
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT
jwt.secret=changeme-replace-with-a-very-long-secret-key-at-least-256-bits
jwt.expiration-ms=86400000

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads
